const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function app(){const context=vm.createContext({console,setTimeout,clearTimeout,AbortController,Date,localStorage:{getItem:()=>null},document:{readyState:'loading',addEventListener(){},querySelectorAll:()=>[]}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../app.js'),'utf8'),context);return {context,run:code=>vm.runInContext(code,context)};}
const holding={ticker:'GOOGL',cusip:'02079K305',putCall:'',shareType:'SH',shares:10};
const snapshot={meta:{instrumentHistoryTickers:['GOOGL'],instrumentHistoryFrom:'2020 Q1'},current:{quarter:'2026 Q2'},history:{holdings:{'2020 Q1':[holding],'2026 Q1':[holding]}}};
const prices={costBasis:{GOOGL:{recent:{buy:100,quarter:'2026 Q1'},allTime:{avg:50,first:'2020 Q1',last:'2026 Q2'}}}};
function fixture(){const a=app();a.context.holding=structuredClone(holding);a.context.snapshot=structuredClone(snapshot);a.context.quote=structuredClone(prices);return a;}
test('verified share classes display valid estimates instead of blanket history suppression',()=>{const a=fixture();assert.equal(a.run('holdingCostState(holding,snapshot,quote).basis.recent.buy'),100);a.run('snapshot.history.holdings["2026 Q1"][0].cusip="different"');assert.equal(a.run('holdingCostState(holding,snapshot,quote).reason'),'classes');});
test('old averages remain hidden until verified splits are recalculated',()=>{const a=fixture();a.run('snapshot.meta.shareActions=[{ticker:"GOOGL",quarter:"2022 Q3"}]');assert.equal(a.run('holdingCostState(holding,snapshot,quote).basis.allTime'),null);a.run('quote.costBasis.GOOGL.splitAdjustedThrough="2026 Q2"');assert.equal(a.run('holdingCostState(holding,snapshot,quote).basis.allTime.avg'),50);});
test('reentry never uses a recent estimate from before the current holding run',()=>{const a=fixture();a.run('quote.costBasis.GOOGL.allTime.first="2026 Q2"');assert.equal(a.run('holdingCostState(holding,snapshot,quote).reason'),'stale_cost');});
test('units, scope, options, principal and archive retain explicit reasons',()=>{for(const [reason,code] of [['units','snapshot.current.valueQuality={}'],['scope','snapshot.meta.reportingTransition={fromQuarter:"2026 Q2",comparisonScopeChanged:true}'],['option','holding.putCall="CALL"'],['principal','holding.shareType="PRN"'],['archive','snapshot.meta.snapshotType="archived"']]){const a=fixture();a.run(code);assert.equal(a.run('holdingCostState(holding,snapshot,quote).reason'),reason);}});
test('cost differences render negative, zero and small positive values',()=>{const a=fixture();assert.match(a.run('costGapHTML(costGap(150,100))'),/现价高于加仓参考价.*50.0%/);assert.match(a.run('costGapHTML(costGap(100,100))'),/现价等于加仓参考价.*0.0%/);assert.match(a.run('costGapHTML(costGap(95,100))'),/现价低于加仓参考价.*5.0%/);assert.equal(a.run('costGap(0,100)'),null);assert.equal(a.run('costGap(100,0)'),null);assert.ok(!a.run('costGapHTML(null)').includes('NaN'));});
